// Build script: simplifies Brazil states GeoJSON into compact SVG paths.
// Usage: node scripts/buildBrazilGeo.js
const fs = require('fs');
const path = require('path');

const RAW = path.join(__dirname, '..', 'brazil-raw.json');
const OUT = path.join(__dirname, '..', 'src', 'data', 'brazilGeo.js');

const raw = JSON.parse(fs.readFileSync(RAW, 'utf8'));

// ---- Douglas-Peucker simplification (in lng/lat degrees) ----
function perpDist(p, a, b) {
  const dx = b[0] - a[0], dy = b[1] - a[1];
  if (dx === 0 && dy === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy);
  const x = a[0] + t * dx, y = a[1] + t * dy;
  return Math.hypot(p[0] - x, p[1] - y);
}
function dp(pts, eps) {
  if (pts.length < 3) return pts;
  let max = 0, idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perpDist(pts[i], pts[0], pts[pts.length - 1]);
    if (d > max) { max = d; idx = i; }
  }
  if (max > eps) {
    const l = dp(pts.slice(0, idx + 1), eps);
    const r = dp(pts.slice(idx), eps);
    return l.slice(0, -1).concat(r);
  }
  return [pts[0], pts[pts.length - 1]];
}

// ---- Bounds ----
let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
function walkCoords(coords, fn) {
  if (typeof coords[0] === 'number') { fn(coords); return; }
  coords.forEach((c) => walkCoords(c, fn));
}
raw.features.forEach((f) =>
  walkCoords(f.geometry.coordinates, ([x, y]) => {
    if (x < minLng) minLng = x;
    if (x > maxLng) maxLng = x;
    if (y < minLat) minLat = y;
    if (y > maxLat) maxLat = y;
  })
);

// ---- Projection to SVG viewBox ----
const W = 600, H = 600, PAD = 20;
const lngRange = maxLng - minLng;
const latRange = maxLat - minLat;
const scale = Math.min((W - 2 * PAD) / lngRange, (H - 2 * PAD) / latRange);
const offsetX = (W - lngRange * scale) / 2 - minLng * scale;
const offsetY = (H - latRange * scale) / 2 + maxLat * scale;
function project(lng, lat) {
  return [lng * scale + offsetX, offsetY - lat * scale];
}

const EPS = 0.06; // ~6 km — tune to balance fidelity vs file size

const states = raw.features.map((f) => {
  const sigla = f.properties.sigla;
  const name = f.properties.name;
  const geom = f.geometry;
  const polygons = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
  const paths = [];
  polygons.forEach((poly) => {
    const outer = poly[0];
    if (!outer || outer.length < 4) return;
    const simplified = dp(outer, EPS);
    if (simplified.length < 3) return;
    const projected = simplified.map(([lng, lat]) => project(lng, lat));
    let pminx = Infinity, pmaxx = -Infinity, pminy = Infinity, pmaxy = -Infinity;
    projected.forEach(([x, y]) => {
      if (x < pminx) pminx = x;
      if (x > pmaxx) pmaxx = x;
      if (y < pminy) pminy = y;
      if (y > pmaxy) pmaxy = y;
    });
    const bboxArea = (pmaxx - pminx) * (pmaxy - pminy);
    if (bboxArea < 2) return; // drop micro-islands
    const d =
      'M' +
      projected.map((p) => p[0].toFixed(1) + ',' + p[1].toFixed(1)).join('L') +
      'Z';
    paths.push(d);
  });

    // ---- True polygon centroid (Shoelace / Green's theorem) ----
  function polygonCentroid(pts) {
    let area = 0, pcx = 0, pcy = 0;
    const n = pts.length;
    for (let i = 0, j = n - 1; i < n; j = i++) {
      const xi = pts[i][0], yi = pts[i][1];
      const xj = pts[j][0], yj = pts[j][1];
      const cross = xi * yj - xj * yi;
      area += cross;
      pcx += (xi + xj) * cross;
      pcy += (yi + yj) * cross;
    }
    area /= 2;
    if (Math.abs(area) < 1e-10) {
      // Degenerate — fall back to average
      const avg = pts.reduce((s, p) => [s[0] + p[0], s[1] + p[1]], [0, 0]);
      return [avg[0] / pts.length, avg[1] / pts.length];
    }
    return [pcx / (6 * area), pcy / (6 * area)];
  }

  // Pick polygon with largest signed area
  let bigPoly = null, bigArea = 0;
  polygons.forEach((poly) => {
    const outer = poly[0];
    if (!outer || outer.length < 3) return;
    let a = 0;
    for (let i = 0, j = outer.length - 1; i < outer.length; j = i++) {
      a += outer[i][0] * outer[j][1] - outer[j][0] * outer[i][1];
    }
    if (Math.abs(a) > bigArea) { bigArea = Math.abs(a); bigPoly = outer; }
  });

  let cx = 0, cy = 0;
  if (bigPoly) {
    const [clng, clat] = polygonCentroid(bigPoly);
    const proj = project(clng, clat);
    cx = Math.round(proj[0]);
    cy = Math.round(proj[1]);
  }
  return { sigla, name, paths, labelX: cx, labelY: cy };
});

const header =
  '// AUTO-GENERATED by scripts/buildBrazilGeo.js\n' +
  '// Source: codeforamerica/click_that_hood brazil-states.geojson (IBGE-derived)\n' +
  '// Simplified with Douglas-Peucker (eps=' + EPS + ' deg) and projected to SVG viewBox.\n\n';

const body =
  'export const BRAZIL_VIEWBOX = "0 0 ' + W + ' ' + H + '";\n\n' +
  'export const BRAZIL_GEO_STATES = ' + JSON.stringify(states) + ';\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log('Wrote', OUT);
console.log('Size KB:', ((header.length + body.length) / 1024).toFixed(1));
console.log('States:', states.length);
